---
title: "Untitled"
author: "Damon Bayer"
date: "11/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(stemr)
library(tidyverse)
library(tidybayes)
library(scales)
library(coda)
library(cowplot)
library(extraDistr)
source('~/Documents/stemr_oc/stemr_functions.R')

# oc_data <- read_rds("data/oc_data.rds")
oc_data <- read_rds("data/oc_data_no_snf.rds")

lump_oc_data <-
  function(oc_data,
           time_interval_in_days,
           first_day = "0000-01-01",
           last_day = "9999-12-31") {
    oc_data %>%
      filter(date >= lubridate::ymd(first_day),
             date <= lubridate::ymd(last_day)) %>%
      group_by(lump = as.integer(floor((max(date) - date) / time_interval_in_days))) %>%
      filter(n() == time_interval_in_days) %>%
      dplyr::summarize(start_date = min(date),
                       end_date = max(date),
                       cases = sum(cases),
                       tests = sum(tests),
                       deaths = sum(deaths)) %>%
      dplyr::select(-lump) %>%
      arrange(start_date)
  }

lumped_oc_data <- lump_oc_data(oc_data, time_interval_in_days = 7, first_day = "2020-03-30", last_day = "2020-10-11") %>%
  left_join(select(oc_data, end_date = date, lagged_pos_ifr))

dat <- lumped_oc_data %>%
  mutate(time = as.numeric((end_date - min(start_date) + 1L) / 7)) %>%
  select(time, cases, tests, deaths, lagged_pos_ifr)

multi_chain_stem_fit <- list()
multi_chain_stem_fit$n_iterations <- 3000
# multi_chain_stem_fit$stem_fit_list <- read_rds("res_2020_11_23_16_40_41.rds") # nursing home date
multi_chain_stem_fit$stem_fit_list <- read_rds("res_2020_11_24_17_10_22.rds") # no nursing home data
n_chains <- 4
thinning_interval <- 100

popsize <- 3068927L
log_popsize <- log(popsize)

```

## Trace Plots

```{r posterior parameters}
posterior_trace_plot <-
  tidy_draws(extract_stem_parameter_posterior(multi_chain_stem_fit = multi_chain_stem_fit, transform = "estimation")) %>%
  pivot_longer(-starts_with(".")) %>%
  mutate(.chain = as_factor(.chain)) %>%
  ggplot(aes(.iteration, value, color = .chain, group = .chain)) +
  geom_line() +
  facet_grid(name ~ .chain, scales = "free_y") +
  theme_cowplot() +
  theme(legend.position = "none") +
  xlab("Iteration") +
  ylab(NULL)

posterior_trace_plot

posterior_lik_trace_plot <-
  multi_chain_stem_fit$stem_fit_list %>%
  map("results") %>%
  map("posterior") %>%
  map("data_log_lik") %>%
  enframe(name = ".chain", value = "data_log_lik") %>%
  left_join(multi_chain_stem_fit$stem_fit_list %>%
              map("results") %>%
              map("posterior") %>%
              map("data_log_lik") %>%
              enframe(name = ".chain", value = "params_log_prior")) %>%
  unnest(c("data_log_lik", "params_log_prior")) %>%
  mutate(lp = data_log_lik + params_log_prior) %>%
  group_by(.chain) %>%
  mutate(.iteration = row_number()) %>%
  mutate(.draw = tidybayes:::draw_from_chain_and_iteration_(.chain, .iteration)) %>%
  select(starts_with("."), everything()) %>%
  pivot_longer(-starts_with(".")) %>%
  mutate(.chain = as_factor(.chain)) %>%
  ggplot(aes(.iteration, value, color = .chain, group = .chain)) +
  geom_line() +
  facet_grid(name ~ .chain, scales = "free_y") +
  theme_cowplot() +
  theme(legend.position = "none")

posterior_lik_trace_plot
```

